### ISSUE TITLE
What is mwe_file?

### ISSUE THREAD

**Issue by dwaydwaydway** [wanghm92/rw_fg#3]
https://github.com/wanghm92/rw_fg/blob/d84bc6a6a0aa02b9327a949869153165d4928524/dataset/scripts/purification/clean.py#L288

**Comment by JiyangZhang** [comment]
Can you provide the nwes.json for processing the dataset? Thanks! @wanghm92

**Comment by wanghm92** [comment]
So sorry for the late response to this long standing issue, didn't get email notifications, added by the latest commit.
